#DATA PATH
data_dir: /homes_unix/jlegrand/data/Memento
output_dir: /homes_unix/jlegrand/data/Memento/output
bids_dir: "/georges/memento/BIDS"
raw_phenotypes: "/bigdata/jlegrand/data/Memento/phenotypes.tsv"
augmented_phenotypes: "/bigdata/jlegrand/data/Memento/output/augmented_phenotypes.csv"
connectivity_matrices: "/homes_unix/jlegrand/data/Memento/output/connectivity"

#FMRI STUDY PARAMETERS
confounds_strategy:
  strategy: ["high_pass", "motion", "wm_csf"]
  motion: "basic"
  wm_csf: "basic"
alpha: 0.05

#TESTS
seed: 1234
age_tol: 1