#DATA PATH
data_dir: /homes_unix/jlegrand/data/Memento
output_dir: /homes_unix/jlegrand/data/Memento/output
bids_dir: "/georges/memento/BIDS"
connectivity_matrices: "/homes_unix/jlegrand/data/Memento/output/connectivity"
statresults: "/homes_unix/jlegrand/data/Memento/output/statresults"
volumes: /bigdata/jlegrand/data/Memento/intracranial_volumes/20240307_synthseg_volumes.csv
custom_atlases : /homes_unix/jlegrand/data/Memento/atlas

#FMRI STUDY PARAMETERS
confounds_strategy:
  strategy: ["high_pass", "motion", "wm_csf"]
  motion: "basic"
  wm_csf: "basic"
alpha: 0.05

# COMPARE MAPS DEFAULT RUN
default_run:
  confounds_strategy:
    strategy: ["high_pass", "motion", "wm_csf"]
    wm_csf: "full"
  SOFT: False
  ATLAS: "schaeffer200"
  CLEAN_SIGNAL: True
  MACRO_LABELS: True
  NAME: "default"
  BALANCE_STRAT: []


#TESTS
seed: 1234
age_tol: 1
sex_prop_tol: 0.1