# Non standard yml, to be parsed with https://github.com/mkaranasou/pyaml_env
#DATA PATH
data_dir: !ENV ${HOME}/data/Memento
output_dir: !ENV ${HOME}/data/Memento/output
bids_dir: "/georges/memento/BIDS"
connectivity_matrices: "/homes_unix/jlegrand/data/Memento/output/connectivity"
statresults: "/homes_unix/jlegrand/data/Memento/output/statresults"
custom_atlases : !ENV ${HOME}/data/Memento/atlas

# CREATE MAPS DEFAULT RUN
default_run:
  confounds_strategy:
    strategy: ["high_pass", "motion", "wm_csf"]
    wm_csf: "full"
  SOFT: False
  ATLAS: "schaeffer200"
  CLEAN_SIGNAL: True
  MACRO_LABELS: True
  NAME: "default"
  BALANCE_STRAT: []


#TESTS
seed: 1234
age_tol: 1
sex_prop_tol: 0.1
alpha: 0.05